[project]
name = "mcp-02"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "httpx>=0.28.1",
    "mcp[cli]>=1.25.0",
    "playwright>=1.57.0",
    "pyyaml>=6.0.3",
]
